table DimComercial
	lineageTag: b221960e-9508-4d8d-a8bc-07e89d00d04e

	column ComercialKey
		dataType: int64
		formatString: 0
		lineageTag: 6169a252-9de2-4518-9362-1a9615f0225b
		summarizeBy: none
		sourceColumn: ComercialKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Comercial
		dataType: string
		lineageTag: bf275e46-f2bf-48ad-a317-d80541c78ceb
		summarizeBy: none
		sourceColumn: Comercial

		annotation SummarizationSetBy = Automatic

	column Zona
		dataType: string
		lineageTag: 5d08fab8-09a7-4144-a03b-a77c6cde43a9
		summarizeBy: none
		sourceColumn: Zona

		annotation SummarizationSetBy = Automatic

	partition DimComercial = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\rhermosod\Downloads\Taller_PowerBI_IA_Datos_v2.xlsx"), null, true),
				    DimComercial_Sheet = Origen{[Item="DimComercial",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(DimComercial_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ComercialKey", Int64.Type}, {"Comercial", type text}, {"Zona", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

