table DimFecha
	lineageTag: dbfca9df-6472-4a74-8750-01f9c6cdcf74

	column FechaKey
		dataType: int64
		formatString: 0
		lineageTag: 27b5d366-9f6b-42b5-910a-3cfafa730207
		summarizeBy: none
		sourceColumn: FechaKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: d663ba7c-15bd-4cfc-8980-e8d8d1ccfb41
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: bb14c202-e592-47e7-bfcb-549f05342d51
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: ab5e593c-e1b6-4487-be30-ec0757d4f543
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column MesNumero
		dataType: int64
		formatString: 0
		lineageTag: 7d052341-e959-4d24-ab76-08b7f8e7f3ab
		summarizeBy: none
		sourceColumn: MesNumero

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 13be630f-455c-46dd-8881-9c803306a0a2
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	partition DimFecha = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\rhermosod\Downloads\Taller_PowerBI_IA_Datos_v2.xlsx"), null, true),
				    DimFecha_Sheet = Origen{[Item="DimFecha",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(DimFecha_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"FechaKey", Int64.Type}, {"Fecha", type date}, {"Año", Int64.Type}, {"Trimestre", type text}, {"MesNumero", Int64.Type}, {"Mes", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

